# Generated by Django 6.0 on 2026-01-08 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
        migrations.RemoveIndex(
            model_name="customuser",
            name="accounts_cu_usernam_ab560e_idx",
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["last_seen"], name="accounts_pr_last_se_fce1bb_idx"
            ),
        ),
    ]
