# Generated by Django 6.0.1 on 2026-01-22 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="default_wallpaper_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
