# Generated by Django 6.0.1 on 2026-01-16 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Site", "0009_alter_userwallpaper_user"),
        ("accounts", "0002_alter_customuser_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="active_wallpaper",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="profiles_using",
                to="Site.wallpaper",
            ),
        ),
    ]
