# Generated by Django 6.0.1 on 2026-04-07 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_trusted_device_and_device_login_challenge"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="deviceloginchallenge",
            new_name="accounts_de_user_id_67cfed_idx",
            old_name="acc_dl_user_st",
        ),
        migrations.RenameIndex(
            model_name="deviceloginchallenge",
            new_name="accounts_de_expires_bca279_idx",
            old_name="acc_dl_exp",
        ),
    ]
