# Generated by Django 6.0.1 on 2026-04-07 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_merge_email_verify_and_rename_indexes"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="devicerecoverycooldown",
            new_name="accounts_de_user_id_8dba72_idx",
            old_name="acc_rec_usr_bind",
        ),
        migrations.RenameIndex(
            model_name="recoveryemailotp",
            new_name="accounts_re_user_id_9259be_idx",
            old_name="acc_recotp_usr",
        ),
    ]
