# Generated by Django 6.0.1 on 2026-04-07 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_emailverificationotp"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="emailverificationotp",
            new_name="accounts_em_user_id_4ae6ec_idx",
            old_name="accounts_em_user_id_6f1a8b_idx",
        ),
    ]
