# Generated by Django 6.0.1 on 2026-04-09 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_accountbackupcode"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="accountbackupcode",
            new_name="accounts_ac_user_id_73cb29_idx",
            old_name="accounts_ba_user_used_idx",
        ),
    ]
