# Generated by Django 6.0 on 2026-01-08 17:43

import pathlib

import django.core.files.storage
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="DisplayMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField(null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_primary", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        max_length=255,
                        null=True,
                        storage=django.core.files.storage.FileSystemStorage(
                            location=pathlib.PurePosixPath(
                                "/Users/annabelova/Desktop/amica/protected_files"
                            )
                        ),
                        upload_to="",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "original_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("extension", models.CharField(blank=True, max_length=10, null=True)),
                ("category", models.CharField(blank=True, max_length=20, null=True)),
                ("file_size", models.BigIntegerField(default=0)),
                (
                    "uploaded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="DisplayPhoto",
            fields=[
                (
                    "displaymedia_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="media_files.displaymedia",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="media/photos/%Y/%m/%d/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png", "webp", "gif"]
                            )
                        ],
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
            bases=("media_files.displaymedia",),
        ),
        migrations.CreateModel(
            name="DisplayVideo",
            fields=[
                (
                    "displaymedia_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="media_files.displaymedia",
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        upload_to="media/videos/%Y/%m/%d/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["mp4", "mov", "webm"]
                            )
                        ],
                    ),
                ),
                ("duration", models.FloatField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
            bases=("media_files.displaymedia",),
        ),
        migrations.CreateModel(
            name="ImageFile",
            fields=[
                (
                    "file_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="media_files.file",
                    ),
                ),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "thumbnail_small",
                    models.ImageField(
                        blank=True,
                        max_length=255,
                        null=True,
                        storage=django.core.files.storage.FileSystemStorage(
                            location=pathlib.PurePosixPath(
                                "/Users/annabelova/Desktop/amica/protected_files"
                            )
                        ),
                        upload_to="thumbnails/small/",
                    ),
                ),
                (
                    "thumbnail_medium",
                    models.ImageField(
                        blank=True,
                        max_length=255,
                        null=True,
                        storage=django.core.files.storage.FileSystemStorage(
                            location=pathlib.PurePosixPath(
                                "/Users/annabelova/Desktop/amica/protected_files"
                            )
                        ),
                        upload_to="thumbnails/medium/",
                    ),
                ),
                (
                    "dominant_color",
                    models.CharField(blank=True, max_length=7, null=True),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("media_files.file",),
        ),
        migrations.CreateModel(
            name="VideoFile",
            fields=[
                (
                    "file_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="media_files.file",
                    ),
                ),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("media_files.file",),
        ),
        migrations.AddIndex(
            model_name="displaymedia",
            index=models.Index(
                fields=["content_type", "object_id", "is_active", "is_primary"],
                name="media_files_content_402632_idx",
            ),
        ),
    ]
