# Generated by Django 6.0 on 2026-01-08 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("media_files", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="displaymedia",
            name="media_files_content_402632_idx",
        ),
        migrations.AddIndex(
            model_name="file",
            index=models.Index(
                fields=["uploaded_at"], name="media_files_uploade_1b6a9b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="file",
            index=models.Index(
                fields=["category", "uploaded_at"],
                name="media_files_categor_21e2f8_idx",
            ),
        ),
        migrations.RemoveField(
            model_name="displaymedia",
            name="is_active",
        ),
    ]
