# Generated by Django 5.2.9 on 2026-01-02 18:37

import pathlib

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media_files", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(
                blank=True,
                max_length=255,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(
                    location=pathlib.PurePosixPath(
                        "/Users/annabelova/Desktop/amica/protected_files"
                    )
                ),
                upload_to="",
            ),
        ),
        migrations.AlterField(
            model_name="imagefile",
            name="thumbnail_medium",
            field=models.ImageField(
                blank=True,
                max_length=255,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(
                    location=pathlib.PurePosixPath(
                        "/Users/annabelova/Desktop/amica/protected_files"
                    )
                ),
                upload_to="thumbnails/medium/",
            ),
        ),
        migrations.AlterField(
            model_name="imagefile",
            name="thumbnail_small",
            field=models.ImageField(
                blank=True,
                max_length=255,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(
                    location=pathlib.PurePosixPath(
                        "/Users/annabelova/Desktop/amica/protected_files"
                    )
                ),
                upload_to="thumbnails/small/",
            ),
        ),
    ]
