# Generated by Django 6.0 on 2026-01-08 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("media_files", "0003_displaymedia_media_files_content_9d3d49_idx"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="displaymedia",
            index=models.Index(
                fields=["content_type", "object_id", "is_primary"],
                name="displaymedia_primary_idx",
            ),
        ),
    ]
