# Generated by Django 6.0 on 2026-01-08 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("media_files", "0004_displaymedia_displaymedia_primary_idx"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="displaymedia",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="displaymedia",
            name="media_files_content_9d3d49_idx",
        ),
        migrations.RemoveIndex(
            model_name="displaymedia",
            name="displaymedia_primary_idx",
        ),
        migrations.AddIndex(
            model_name="displaymedia",
            index=models.Index(
                fields=["content_type", "object_id", "is_primary", "created_at"],
                name="displaymedia_primary_created_idx",
            ),
        ),
    ]
