# Generated by Django 6.0.1 on 2026-01-21 17:46

import django.core.files.storage
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "media_files",
            "0004_alter_file_file_alter_imagefile_thumbnail_medium_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="audiofile",
            name="cover",
            field=models.ImageField(
                blank=True,
                max_length=255,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(
                    location=pathlib.PurePosixPath("/app/protected_files")
                ),
                upload_to="thumbnails/cover/",
            ),
        ),
    ]
