# Generated by Django 6.0 on 2026-01-08 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("media_files", "0005_alter_displaymedia_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="displaymedia",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RenameIndex(
            model_name="displaymedia",
            new_name="dm_primary_created",
            old_name="displaymedia_primary_created_idx",
        ),
    ]
