# Generated by Django 6.0.1 on 2026-01-21 17:55

import django.core.files.storage
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media_files", "0006_alter_audiofile_cover_alter_file_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audiofile",
            name="cover",
            field=models.ImageField(
                blank=True,
                max_length=255,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(
                    location=pathlib.PurePosixPath("/app/protected_files")
                ),
                upload_to="thumbnails/cover/",
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(
                blank=True,
                max_length=255,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(
                    location=pathlib.PurePosixPath("/app/protected_files")
                ),
                upload_to="",
            ),
        ),
        migrations.AlterField(
            model_name="imagefile",
            name="thumbnail_medium",
            field=models.ImageField(
                blank=True,
                max_length=255,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(
                    location=pathlib.PurePosixPath("/app/protected_files")
                ),
                upload_to="thumbnails/medium/",
            ),
        ),
        migrations.AlterField(
            model_name="imagefile",
            name="thumbnail_small",
            field=models.ImageField(
                blank=True,
                max_length=255,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(
                    location=pathlib.PurePosixPath("/app/protected_files")
                ),
                upload_to="thumbnails/small/",
            ),
        ),
    ]
