# Generated by Django 6.0.1 on 2026-01-26 22:24

import django.core.files.storage
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "media_files",
            "0016_alter_imagefile_options_displayphoto_dominant_color_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="audiofile",
            name="cover",
            field=models.ImageField(
                blank=True,
                max_length=255,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(
                    location=pathlib.PurePosixPath("/app/protected_files")
                ),
                upload_to="thumbnails/cover/",
            ),
        ),
        migrations.AlterField(
            model_name="displayphoto",
            name="image",
            field=models.ImageField(
                storage=django.core.files.storage.FileSystemStorage(
                    location=pathlib.PurePosixPath("/app/protected_files")
                ),
                upload_to="media/photos/%Y/%m/%d/",
            ),
        ),
        migrations.AlterField(
            model_name="displayphoto",
            name="thumbnail_medium",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(
                    location=pathlib.PurePosixPath("/app/protected_files")
                ),
                upload_to="display/thumbnails/640/",
            ),
        ),
        migrations.AlterField(
            model_name="displayphoto",
            name="thumbnail_small",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(
                    location=pathlib.PurePosixPath("/app/protected_files")
                ),
                upload_to="display/thumbnails/180/",
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(
                blank=True,
                max_length=255,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(
                    location=pathlib.PurePosixPath("/app/protected_files")
                ),
                upload_to="",
            ),
        ),
    ]
