# Generated by Django 6.0.1 on 2026-04-04 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("media_files", "0017_alter_audiofile_cover_alter_displayphoto_image_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="file",
            options={"ordering": ["uploaded_at", "pk"]},
        ),
    ]
