# Generated by Django 6.0.1 on 2026-01-27 23:23

import django.core.files.storage
import django.core.validators
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media_files", "0018_alter_displayphoto_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audiofile",
            name="cover",
            field=models.ImageField(
                blank=True,
                max_length=255,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(
                    location=pathlib.PurePosixPath(
                        "/Users/annabelova/Desktop/amica/protected_files"
                    )
                ),
                upload_to="thumbnails/cover/",
            ),
        ),
        migrations.AlterField(
            model_name="displayphoto",
            name="image",
            field=models.ImageField(
                storage=django.core.files.storage.FileSystemStorage(
                    location=pathlib.PurePosixPath(
                        "/Users/annabelova/Desktop/amica/protected_files"
                    )
                ),
                upload_to="media/photos/%Y/%m/%d/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "webp", "gif"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="displayphoto",
            name="thumbnail_medium",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(
                    location=pathlib.PurePosixPath(
                        "/Users/annabelova/Desktop/amica/protected_files"
                    )
                ),
                upload_to="display/thumbnails/640/",
            ),
        ),
        migrations.AlterField(
            model_name="displayphoto",
            name="thumbnail_small",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(
                    location=pathlib.PurePosixPath(
                        "/Users/annabelova/Desktop/amica/protected_files"
                    )
                ),
                upload_to="display/thumbnails/180/",
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(
                blank=True,
                max_length=255,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(
                    location=pathlib.PurePosixPath(
                        "/Users/annabelova/Desktop/amica/protected_files"
                    )
                ),
                upload_to="",
            ),
        ),
        migrations.AlterField(
            model_name="imagefile",
            name="thumbnail_medium",
            field=models.ImageField(
                blank=True,
                max_length=255,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(
                    location=pathlib.PurePosixPath(
                        "/Users/annabelova/Desktop/amica/protected_files"
                    )
                ),
                upload_to="thumbnails/medium/",
            ),
        ),
        migrations.AlterField(
            model_name="imagefile",
            name="thumbnail_small",
            field=models.ImageField(
                blank=True,
                max_length=255,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(
                    location=pathlib.PurePosixPath(
                        "/Users/annabelova/Desktop/amica/protected_files"
                    )
                ),
                upload_to="thumbnails/small/",
            ),
        ),
    ]
