# Generated by Django 6.0.1 on 2026-01-27 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media_files", "0025_alter_audiofile_cover_alter_displayphoto_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="displayphoto",
            name="dominant_color",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="imagefile",
            name="dominant_color",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
