# Generated by Django 6.0.1 on 2026-01-18 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Site", "0002_initial"),
        ("media_files", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmemberwallpaper",
            name="file",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="media_files.file"
            ),
        ),
        migrations.AddField(
            model_name="chatmemberwallpaper",
            name="member",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wallpaper",
                to="Site.chatmember",
            ),
        ),
        migrations.AddField(
            model_name="chatwallpaper",
            name="chat",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shared_wallpaper",
                to="Site.chat",
            ),
        ),
        migrations.AddField(
            model_name="chatwallpaper",
            name="file",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="media_files.file"
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contacts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="in_contacts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="chat",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="Site.chat",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="file",
            field=models.ManyToManyField(
                blank=True, related_name="messages", to="media_files.file"
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="forwarded",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="forwarded_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="reply_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replies",
                to="Site.message",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="user",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sent_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="messagereaction",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="message_reactions",
                to="Site.message",
            ),
        ),
        migrations.AddField(
            model_name="messagereaction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_reactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="messagerecipient",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipients",
                to="Site.message",
            ),
        ),
        migrations.AddField(
            model_name="messagerecipient",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="message_recipients",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="viewed_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="viewed_messages",
                through="Site.MessageRecipient",
                through_fields=("message", "user"),
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userwallpaper",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wallpapers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userwallpaper",
            name="wallpaper",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Site.wallpaper"
            ),
        ),
        migrations.AddIndex(
            model_name="chatmember",
            index=models.Index(fields=["user", "chat"], name="user_chat_idx"),
        ),
        migrations.AddConstraint(
            model_name="chatmember",
            constraint=models.UniqueConstraint(
                fields=("chat", "user"), name="unique_chat_member"
            ),
        ),
        migrations.AddIndex(
            model_name="chat",
            index=models.Index(
                fields=["-created_at", "chat_type"], name="Site_chat_created_7fb74b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(fields=["owner"], name="contact_owner_idx"),
        ),
        migrations.AddConstraint(
            model_name="contact",
            constraint=models.UniqueConstraint(
                fields=("owner", "user"), name="unique_contact_per_owner"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="messagereaction",
            unique_together={("message", "user")},
        ),
        migrations.AddIndex(
            model_name="messagerecipient",
            index=models.Index(
                fields=["user", "read_date", "is_deleted"],
                name="Site_messag_user_id_c58ee6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="messagerecipient",
            index=models.Index(
                fields=["message", "user"], name="Site_messag_message_142270_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="messagerecipient",
            index=models.Index(
                fields=["user", "is_deleted", "message"],
                name="Site_messag_user_id_a02693_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="messagerecipient",
            index=models.Index(
                fields=["user", "is_deleted", "read_date"],
                name="Site_messag_user_id_178e4f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="messagerecipient",
            index=models.Index(
                fields=["user", "is_deleted", "read_date", "message"],
                name="Site_messag_user_id_e4171c_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="messagerecipient",
            unique_together={("message", "user")},
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["chat", "-date", "id"], name="Site_messag_chat_id_1117c6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["user", "-date"], name="Site_messag_user_id_d7d165_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["chat", "is_deleted", "-date"], name="msg_chat_isdel_date_idx"
            ),
        ),
    ]
