# Generated by Django 6.0 on 2026-01-08 20:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Site", "0003_initial"),
        ("media_files", "0003_displaymedia_media_files_content_9d3d49_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="chat",
            name="Site_chat_id_26b277_idx",
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(fields=["owner"], name="contact_owner_idx"),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["chat", "is_deleted", "-date"], name="msg_chat_isdel_date_idx"
            ),
        ),
    ]
