# Generated by Django 6.0.1 on 2026-01-20 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Site", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallpaper",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[("photo", "Photo"), ("video", "Video")],
                max_length=10,
            ),
        ),
    ]
