# Generated by Django 6.0.1 on 2026-03-13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Site", "0004_wallpaper_type"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="messagereaction",
            unique_together={("message", "user", "reaction_type")},
        ),
    ]

