# Generated by Django 6.0 on 2026-01-08 20:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Site", "0004_remove_chat_site_chat_id_26b277_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="messagerecipient",
            index=models.Index(
                fields=["user", "is_deleted", "read_date", "message"],
                name="Site_messag_user_id_e4171c_idx",
            ),
        ),
    ]
