# Generated by Django 6.0.1 on 2026-01-16 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Site", "0005_messagerecipient_site_messag_user_id_e4171c_idx"),
        (
            "media_files",
            "0007_alter_file_file_alter_imagefile_thumbnail_medium_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatMemberWallpaper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="media_files.file",
                    ),
                ),
                (
                    "member",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallpaper",
                        to="Site.chatmember",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChatWallpaper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chat",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shared_wallpaper",
                        to="Site.chat",
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="media_files.file",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Wallpaper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="media_files.file",
                    ),
                ),
            ],
        ),
    ]
