# Generated by Django 6.0.1 on 2026-03-26 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Site", "0005_alter_messagereaction_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="is_deleted",
        ),
        migrations.AddField(
            model_name="message",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
