# Generated by Django 6.0.1 on 2026-03-26 21:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Site", "0006_remove_message_is_deleted_message_deleted_at"),
        ("media_files", "0017_alter_audiofile_cover_alter_displayphoto_image_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="message",
            name="msg_chat_isdel_date_idx",
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["chat", "deleted_at", "-date"], name="msg_chat_deleted_date_idx"
            ),
        ),
    ]
