# Generated by Django 6.0.1 on 2026-01-16 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Site", "0007_userwallpaper"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallpaper",
            name="file",
            field=models.FileField(upload_to="wallpapers/"),
        ),
    ]
