# Generated by Django 6.0.1 on 2026-03-26 22:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Site", "0007_remove_message_msg_chat_isdel_date_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="messagerecipient",
            name="Site_messag_user_id_c58ee6_idx",
        ),
        migrations.RemoveIndex(
            model_name="messagerecipient",
            name="Site_messag_user_id_a02693_idx",
        ),
        migrations.RemoveIndex(
            model_name="messagerecipient",
            name="Site_messag_user_id_178e4f_idx",
        ),
        migrations.RemoveIndex(
            model_name="messagerecipient",
            name="Site_messag_user_id_e4171c_idx",
        ),
        migrations.AddField(
            model_name="messagerecipient",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="messagerecipient",
            index=models.Index(
                fields=["user", "read_date", "deleted_at"],
                name="Site_messag_user_id_b4cf4a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="messagerecipient",
            index=models.Index(
                fields=["user", "deleted_at", "message"],
                name="Site_messag_user_id_1f490c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="messagerecipient",
            index=models.Index(
                fields=["user", "deleted_at", "read_date"],
                name="Site_messag_user_id_bdce2c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="messagerecipient",
            index=models.Index(
                fields=["user", "deleted_at", "read_date", "message"],
                name="Site_messag_user_id_22322f_idx",
            ),
        ),
        migrations.RemoveField(
            model_name="messagerecipient",
            name="is_deleted",
        ),
    ]
