# Generated by Django 6.0.1 on 2026-01-16 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Site", "0008_alter_wallpaper_file"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="userwallpaper",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wallpapers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
