# Generated by Django 6.0.1 on 2026-01-17 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Site", "0009_alter_userwallpaper_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userwallpaper",
            name="wallpaper",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Site.wallpaper"
            ),
        ),
    ]
