from django.contrib.auth import get_user_model
from django.utils import timezone


def run():
    User = get_user_model()

    admin_email = "a@a.com"
    if not User.objects.filter(email=admin_email).exists():
        admin = User.objects.create_superuser(
            username="admin", email=admin_email, password="admin"
        )
        print(f"Created admin: {admin_email}")

    names = [
        "Calista Monroe",
        "Ayla Reed",
        "Aurora Sinclair II",
        "Amarantha Blackwood",
        "Luna Everhart",
        "Isla Montgomery",
        "Seraphina Vale",
        "Elara Whitlock",
        "Ophelia Drake",
        "Selene Hawthorne",
        "Aria Lennox",
        "Violet Ashcroft",
        "Juliette March",
        "Cecilia Fairchild",
        "Miranda Sterling",
        "Arabella Knight",
        "Evangeline Frost",
        "Tatiana Hawke",
        "Imogen Blackwell",
        "Celeste Donovan",
        "Dahlia Prescott",
        "Fiona Kingsley",
        "Giselle Marlowe",
        "Helena Sinclair",
        "Isolde Ravenswood",
        "Jocelyn Carlisle",
        "Katerina Voss",
        "Liliana Drake",
        "Matilda Ravens",
        "Natalia Storm",
        "Octavia Gray",
        "Penelope Ward",
        "Quintessa Vale",
        "Rosalind Harper",
        "Selina Montague",
        "Thalia Brooks",
        "Ursula Knightley",
        "Valentina Frost",
        "Wilhelmina Cross",
        "Xanthe Beaumont",
        "Yvette Sterling",
        "Zara Hawthorne",
        "Althea Whitlock",
        "Briony Vale",
        "Camilla Sinclair",
        "Delilah Hawke",
        "Elodie Drake",
        "Francesca Montgomery",
        "Genevieve Monroe",
        "Harper Sterling",
        "Isabella Lennox",
        "Juliana Frost",
        "Katrina Blackwood",
        "Lorelei Ward",
        "Marcella Ashcroft",
        "Noemi Prescott",
        "Odette Brooks",
        "Paloma Gray",
        "Quilla Whitlock",
        "Raphaela Marlowe",
        "Sabrina Montague",
        "Tatienne Vale",
        "Ulla Sinclair",
        "Veronica Hawthorne",
        "Wilma Frost",
        "Xenia Knight",
        "Yara Sterling",
        "Zinnia Cross",
        "Amelia Raven",
        "Bianca Monroe",
        "Carina Drake",
        "Diana Hawke",
        "Emilia Blackwood",
        "Frida Whitlock",
        "Gabriella Storm",
        "Harlow Sinclair",
        "Iris Montgomery",
        "Jemima Frost",
        "Klara Vale",
        "Leona Ashcroft",
        "Melina Prescott",
        "Nadia Brooks",
        "Olivia Ward",
        "Philippa Gray",
        "Quinn Marlowe",
        "Rhiannon Montague",
        "Sienna Hawthorne",
        "Tatiana Cross",
        "Uma Sinclair",
        "Vivienne Drake",
        "Willa Frost",
        "Ximena Knight",
        "Yolanda Sterling",
        "Zelda Blackwood",
        "Aurelia Monroe",
        "Beatrix Whitlock",
        "Cassandra Vale",
        "Daphne Ashcroft",
        "Eloise Prescott",
        "Felicity Brooks",
        "Georgina Gray",
        "Hermione Marlowe",
        "Ivy Montague",
        "Juliet Hawthorne",
        "Kylie Cross",
    ]

    for i, full_name in enumerate(names, start=1):
        first_name, last_name = full_name.split(" ", 1)
        email = f"user{i}@example.com"

        if not User.objects.filter(email=email).exists():
            user = User.objects.create_user(
                username=full_name.replace(" ", " "),
                email=email,
                password="password123",
                first_name=first_name,
                last_name=last_name,
            )
            print(f"Created user: {email} with username: {user.username}")
